version: 1.0
data:
    trg: ['data/raw/train.vi','data/raw/tst2012.vi','data/raw/tst2013.vi']
    src: ['data/raw/train.en','data/raw/tst2012.en','data/raw/tst2012.en']
    vocab: ["data/vocab/EN.state", "data/vocab/VI.state"]
    processed: ['data/processed/train.pkl','data/processed/valid.pkl','data/processed/test.pkl']
    save_vocab: True
    save_processed: True
params:
    hidden_size: 512
    embed_size: 128
    max_len: 100
    vocab_size: 20000
    
hyperparams: 
    epochs: 100
    batch_size: 64
    learning_rate: 0.0001
    grad_clip: 10.0
  
model:
    encoder: 
        n_layers: 2
        dropout: 0.5
    decoder:
        n_layers: 1
        dropout: 0.5
    seq2seq:
        teacher_forcing_ratio: 0.5
    save: 'save/seq2seq.pt'
    patience: 5
    min_delta: 0.0

predictor:
    beamsearch: True
    beam_size: 4
    candidates: 1
    sos_token: 2
    eos_token: 3